GRANT CONNECT ON DATABASE taskdb TO admin;
GRANT ALL PRIVILEGES ON SCHEMA task_manager TO admin;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA task_manager TO admin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA task_manager TO admin;

CREATE ROLE app LOGIN PASSWORD 'app123';
GRANT CONNECT ON DATABASE taskdb TO app;
GRANT USAGE ON SCHEMA task_manager TO app;
GRANT SELECT ON ALL TABLES IN SCHEMA task_manager TO app;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA task_manager TO app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA task_manager TO app;

CREATE ROLE readonly LOGIN PASSWORD 'readonly123';
GRANT CONNECT ON DATABASE taskdb TO readonly;
GRANT USAGE ON SCHEMA task_manager TO readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA task_manager TO readonly;
